name       : libftdi1
version    : '1.5'
release    : 6
source     :
    - https://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.5.tar.bz2 : 7c7091e9c86196148bd41177b4590dccb1510bfe6cea5bf7407ff194482eb049
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An open source library to talk to FTDI chips
description: |
    libFTDI is an open source library to talk to FTDI chips FT232BM, FT245BM, FT2232C, FT2232D, FT245R, FT232H and FT230X including the popular bitbang mode.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(libconfuse)
    - libboost-devel # For tests and C++ bindings.
setup      : |
    %cmake -DBUILD_TESTS=ON \
        -DEXAMPLES=OFF \
        -DFTDI_EEPROM=ON \
        -DFTDIPP=ON \
        -DSTATICLIBS=OFF
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
    # Using rmdir to make sure we don't rm something useful in share/.
    rmdir  $installdir/usr/share
check      : |
    %make check
