name       : libftdi1
version    : 1.4
release    : 3
source     :
    - https://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.4.tar.bz2 : ec36fb49080f834690c24008328a5ef42d3cf584ef4060f3a35aa4681cb31b74
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An open source library to talk to FTDI chips
description: |
    libFTDI is an open source library to talk to FTDI chips FT232BM, FT245BM, FT2232C, FT2232D, FT245R, FT232H and FT230X including the popular bitbang mode.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(libconfuse)
setup      : |
    %cmake -DSTATICLIBS=OFF -DEXAMPLES=OFF -DFTDI_EEPROM=ON
build      : |
    %make
install    : |
    %make_install
