name       : libftdi1
version    : 1.3
release    : 1
source     :
    - https://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.3.tar.bz2 : 9a8c95c94bfbcf36584a0a58a6e2003d9b133213d9202b76aec76302ffaa81f4
license    : LGPL-2.1
component  : system.utils
summary    : An open source library to talk to FTDI chips
description: |
    libFTDI is an open source library to talk to FTDI chips FT232BM, FT245BM, FT2232C, FT2232D, FT245R, FT232H and FT230X including the popular bitbang mode. 
builddeps  :
    - pkgconfig(libusb)
    - libboost-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
